name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
        # make depends on uv
      - name: Install dependencies
        run: |
          pip install uv
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Run test coverage
        run: |
          make test-coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=RStructura_qa-auto-engineer-python-project-241
            -Dsonar.organization=rstructura
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=gendiff
